"""add model_name column

Revision ID: 522c06424838
Revises: c55bd95ffc9b
Create Date: 2026-04-21 08:27:03.330155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522c06424838'
down_revision: Union[str, Sequence[str], None] = 'c55bd95ffc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_result', sa.Column('model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_result', 'model_name')
    # ### end Alembic commands ###
