CREATE TABLE IF NOT EXISTS model_result (
    id SERIAL PRIMARY KEY,
    feature_1 DOUBLE PRECISION NOT NULL,
    feature_2 DOUBLE PRECISION NOT NULL,
    feature_3 DOUBLE PRECISION NOT NULL,
    feature_4 DOUBLE PRECISION NOT NULL,
    prediction INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
